## Ejercicio 1.1

### Contar el numero de lineas para cada archivo

In [36]:
bookings = '/Users/giuliagalli/Documents/Master Data Science/Clases Master/challenge/bookings.csv'
searches = '/Users/giuliagalli/Documents/Master Data Science/Clases Master/challenge/searches.csv'

import bz2
import pandas as pd

In [25]:
bz2.decompress?

In [28]:
bz2_bookings = bz2.BZ2File(bookings)

import pandas as pd

In [34]:
data = bz2.decompress(bz2.BZ2File(bookings).read())

OSError: Invalid data stream

data = bz2.decompress(bz2.BZ2File(bookings).read())

In [47]:
df_booking = pd.read_csv(bookings, error_bad_lines=False, sep='^')

/Applications/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (7,8,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [53]:
df_searches = pd.read_csv(searches, error_bad_lines=False, sep='^')

/Applications/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (40,41,42,44) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [48]:
len(df_booking.index)

10000010

In [54]:
len(df_searches.index)

20390198

## Ejercicio 2.1

In [49]:
df_booking.columns

Index(['act_date           ', 'source', 'pos_ctry', 'pos_iata', 'pos_oid  ',
       'rloc          ', 'cre_date           ', 'duration', 'distance',
       'dep_port', 'dep_city', 'dep_ctry', 'arr_port', 'arr_city', 'arr_ctry',
       'lst_port', 'lst_city', 'lst_ctry', 'brd_port', 'brd_city', 'brd_ctry',
       'off_port', 'off_city', 'off_ctry', 'mkt_port', 'mkt_city', 'mkt_ctry',
       'intl', 'route          ', 'carrier', 'bkg_class', 'cab_class',
       'brd_time           ', 'off_time           ', 'pax', 'year', 'month',
       'oid      '],
      dtype='object')

In [50]:
df_booking

,act_date,source,pos_ctry,pos_iata,pos_oid,rloc,cre_date,duration,distance,dep_port,...,route,carrier,bkg_class,cab_class,brd_time,off_time,pax,year,month,oid
0,2013-03-05 00:00:00,1A,DE,a68dd7ae953c8acfb187a1af2dcbe123,1a11ae49fcbf545fd2afc1a24d88d2b7,ea65900e72d71f4626378e2ebd298267,2013-02-22 00:00:00,1708,0,ZRH,...,LHRZRH,VI,T,Y,2013-03-07 08:50:00,2013-03-07 11:33:37,-1.0,2013.0,3.0,NULL
1,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,...,SALATLCLT,NV,L,Y,2013-04-12 13:04:00,2013-04-12 22:05:40,1.0,2013.0,3.0,NULL
2,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,...,CLTATLSAL,NV,U,Y,2013-07-15 07:00:00,2013-07-15 11:34:51,1.0,2013.0,3.0,NULL
3,2013-03-26 00:00:00,1A,AU,0f984b3bb6bd06661c95529bbd6193bc,36472c6dbaf7afec9136ac40364e2794,5ecf00fdcbcec761c43dc7285253d0c1,2013-03-26 00:00:00,30885,0,AKL,...,AKLHKGSVO,XK,G,Y,2013-04-24 23:59:00,2013-04-25 16:06:31,1.0,2013.0,3.0,SYDA82546
4,2013-03-26 00:00:00,1A,AU,0f984b3bb6bd06661c95529bbd6193bc,36472c6dbaf7afec9136ac40364e2794,5ecf00fdcbcec761c43dc7285253d0c1,2013-03-26 00:00:00,30885,0,AKL,...,SVOHKGAKL,XK,G,Y,2013-05-14 20:15:00,2013-05-16 10:44:50,1.0,2013.0,3.0,SYDA82546
5,2013-03-20 00:00:00,1V,US,0283592e45e392871f7e14b1e22a9aaf,2d0f8e7e1bb792625d2f34f221bc38f1,d54708298686de200f8270e7c637af5e,2013-03-20 00:00:00,5923,0,DEN,...,DENLGA,FK,W,Y,2013-04-07 10:23:00,2013-04-07 16:14:24,1.0,2013.0,3.0,NULL
6,2013-03-20 00:00:00,1V,US,0283592e45e392871f7e14b1e22a9aaf,2d0f8e7e1bb792625d2f34f221bc38f1,d54708298686de200f8270e7c637af5e,2013-03-20 00:00:00,5923,0,DEN,...,LGADEN,FK,K,Y,2013-04-11 11:15:00,2013-04-11 13:06:24,1.0,2013.0,3.0,NULL
7,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,NRTSIN,XR,Q,Y,2013-04-14 11:05:00,2013-04-14 17:10:56,2.0,2013.0,3.0,NULL
8,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,SINPEN,WS,Y,Y,2013-04-16 15:45:00,2013-04-16 17:15:29,2.0,2013.0,3.0,NULL
9,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,PENBKK,EQ,Y,Y,2013-04-18 08:00:00,2013-04-18 08:53:56,2.0,2013.0,3.0,NULL
10,2013-03-25 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,BKKHND,XR,B,Y,2013-04-19 22:25:00,2013-04-20 06:36:40,2.0,2013.0,3.0,NULL
11,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,NRTSIN,XR,Q,Y,2013-04-14 11:05:00,2013-04-14 17:10:56,-2.0,2013.0,3.0,NULL
12,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,SINPEN,WS,Y,Y,2013-04-16 15:45:00,2013-04-16 17:15:29,-2.0,2013.0,3.0,NULL
13,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,PENBKK,EQ,Y,Y,2013-04-18 08:00:00,2013-04-18 08:53:56,-2.0,2013.0,3.0,NULL
14,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,BKKHND,XR,B,Y,2013-04-19 22:25:00,2013-04-20 06:36:40,-2.0,2013.0,3.0,NULL
15,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,NRTSIN,XR,Q,Y,2013-04-14 11:05:00,2013-04-14 17:10:56,1.0,2013.0,3.0,NULL
16,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,SINPEN,WS,Y,Y,2013-04-16 15:45:00,2013-04-16 17:15:29,1.0,2013.0,3.0,NULL
17,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,PENBKK,EQ,Y,Y,2013-04-18 08:00:00,2013-04-18 08:53:56,1.0,2013.0,3.0,NULL
18,2013-03-28 00:00:00,1V,JP,5af045902bd23cab579915611d99e1e0,5073861d8597467c33596bfe16f23c56,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,...,BKKHND,XR,B,Y,2013-04-19 22:25:00,2013-04-20 06:36:40,1.0,2013.0,3.0,NULL
19,2013-03-13 00:00:00,1V,CA,f8d15f8b5e04f0cfcb62f299d059beb3,257170d899c9dc7744a83f18c399bc1c,c302645256976e555e80bc46a3f982d7,2013-03-13 00:00:00,11640,0,YYZ,...,YYZTUS,FK,V,Y,2013-04-06 13:28:00,2013-04-06 14:48:17,1.0,2013.0,3.0,NULL
20,2013-03-25 00:00:00,1A,IT,f1c9acf55eb44dedd43734952a9138a6,7f3988fed8c1fe28c882eb979acc046c,57af3d59571623b706c04ac178d5900b,2013-03-12 00:00:00,9240,0,FCO,...,FCOCTA,KK,O,Y,2013-05-25 07:25:00,2013-05-25 08:50:57,-2.0,2013.0,3.0,NULL
21,2013-03-25 00:00:00,1A,IT,f1c9acf55eb44dedd43734952a9138a6,7f3988fed8c1fe28c882eb979acc046c,57af3d59571623b706c04ac178d5900b,2013-03-12 00:00:00,9175,0,FCO,...,FCOCTA,KK,O,Y,2013-05-25 08:30:00,2013-05-25 09:55:57,2.0,2013.0,3.0,NULL
22,2013-03-12 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,194949,102,BDQ,...,BDQDELYYZYWG,CH,N,Y,2013-03-24 20:50:00,2013-03-25 19:34:05,2.0,2013.0,3.0,BDQAK3101
23,2013-03-12 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,194949,102,BDQ,...,YWGYYZBRUBOMAMD,CH,K,Y,2013-08-05 12:35:00,2013-08-07 05:59:19,2.0,2013.0,3.0,BDQAK3101
24,2013-03-13 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,194949,102,BDQ,...,YWGYYZBRUBOMAMD,CH,K,Y,2013-08-05 12:35:00,2013-08-07 05:59:19,-2.0,2013.0,3.0,BDQAK3101
25,2013-03-13 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219429,102,BDQ,...,YWGYYZBRUBOMAMD,CH,K,Y,2013-08-22 10:35:00,2013-08-24 05:59:19,2.0,2013.0,3.0,BDQAK3101
26,2013-03-18 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,...,BDQBOMDEL,CH,T,Y,2013-03-24 19:15:00,2013-03-25 04:33:17,2.0,2013.0,3.0,BDQAK3101
27,2013-03-19 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,...,BDQBOMDEL,CH,T,Y,2013-03-24 19:15:00,2013-03-25 04:33:17,-2.0,2013.0,3.0,BDQAK3101
28,2013-03-19 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,...,BDQDELYYZYWG,CH,N,Y,2013-03-24 20:50:00,2013-03-25 19:34:05,-2.0,2013.0,3.0,BDQAK3101
29,2013-03-19 00:00:00,1A,IN,ce60b5b55af87be62855ef1787b6b13f,4760d231a384bd15c720e217b190bc92,29b689903e7432d637777855f9542d86,2013-03-12 00:00:00,219524,102,BDQ,...,BDQBOMBRUYYZYWG,CH,U,Y,2013-03-24 19:15:00,2013-03-25 19:34:05,2.0,2013.0,3.0,BDQAK3101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9999980,2013-05-07 00:00:00,1P,RO,6c2c5bd84e7950b1590d096546023061,21f8c1f4f6ef8edc26142ec086c7905c,7d360e9b3687ceca882c2adab03e3bd5,2013-05-07 00:00:00,3491,0,OTP,...,LYSZRHOTP,VI,S,Y,2013-06-07 18:55:00,2013-06-08 00:11:02,1.0,2013.0,5.0,NULL
9999981,2013-05-07 00:00:00,1P,DE,c808e9b4d7eaf0fe2a34fd38d265e381,a6561da9ff9fdbae66094468dd46fc86,6aac76be827046526ba3a42331020e58,2013-05-07 00:00:00,225596,187,DUS,...,DUSAUHBNE,KL,O,Y,2013-05-09 21:30:00,2013-05-11 07:15:17,1.0,2013.0,5.0,NULL
9999982,2013-05-07 00:00:00,1P,DE,c808e9b4d7eaf0fe2a34fd38d265e381,a6561da9ff9fdbae66094468dd46fc86,6aac76be827046526ba3a42331020e58,2013-05-07 00:00:00,225596,187,DUS,...,BKKAUH,OJ,V,Y,2013-10-12 08:35:00,2013-10-12 12:13:19,1.0,2013.0,5.0,NULL
9999983,2013-05-07 00:00:00,1P,DE,c808e9b4d7eaf0fe2a34fd38d265e381,a6561da9ff9fdbae66094468dd46fc86,6aac76be827046526ba3a42331020e58,2013-05-07 00:00:00,225596,187,DUS,...,AUHFRA,OJ,V,Y,2013-10-13 08:55:00,2013-10-13 13:26:04,1.0,2013.0,5.0,NULL
9999984,2013-05-07 00:00:00,1P,US,83ccf07a55606976f78e63fcc805f58c,1490c3c5f95f04fa076fe15c775a80a9,495574406352f4cbfbe3f7b0cfaf3079,2013-05-07 00:00:00,5090,0,MAD,...,MADORY,FI,U,Y,2013-05-16 20:20:00,2013-05-16 22:20:30,1.0,2013.0,5.0,NULL
9999985,2013-05-07 00:00:00,1P,US,83ccf07a55606976f78e63fcc805f58c,1490c3c5f95f04fa076fe15c775a80a9,495574406352f4cbfbe3f7b0cfaf3079,2013-05-07 00:00:00,5090,0,MAD,...,ORYMAD,FI,P,F,2013-05-20 07:10:00,2013-05-20 09:10:30,1.0,2013.0,5.0,NULL
9999986,2013-05-07 00:00:00,1P,FR,0f6a9ecd7a375c253600f442e843d8b4,7e079b264d90546fc1b908a8c4e81199,d0d9b78730b7a00319b5ab1b8f738c8a,2013-05-07 00:00:00,41658,0,TXL,...,TXLDME,FX,I,C,2013-06-30 14:05:00,2013-06-30 18:48:05,1.0,2013.0,5.0,NULL
9999987,2013-05-07 00:00:00,1P,FR,0f6a9ecd7a375c253600f442e843d8b4,7e079b264d90546fc1b908a8c4e81199,d0d9b78730b7a00319b5ab1b8f738c8a,2013-05-07 00:00:00,41658,0,TXL,...,DMETXL,FX,T,Y,2013-07-29 11:40:00,2013-07-29 12:23:05,1.0,2013.0,5.0,NULL
9999988,2013-05-07 00:00:00,1P,GR,48619bc6735a3c6508c1b5bbb76b12e6,dd891a67331a4836931e0f462af23a56,87764e21184af39e2accff81d2eae01b,2013-05-07 00:00:00,6726,0,ATH,...,ATHJKH,YK,X,Y,2013-05-07 20:55:00,2013-05-07 21:56:55,1.0,2013.0,5.0,NULL
9999989,2013-05-07 00:00:00,1P,GR,48619bc6735a3c6508c1b5bbb76b12e6,dd891a67331a4836931e0f462af23a56,87764e21184af39e2accff81d2eae01b,2013-05-07 00:00:00,6726,0,ATH,...,JKHATH,YK,M,Y,2013-05-12 12:00:00,2013-05-12 13:01:55,1.0,2013.0,5.0,NULL
9999990,2013-05-07 00:00:00,1P,SE,5924bc3bdf4f7a2461df897a9e41c56b,61f493dfd620a71b1301a4c65d55181b,ba3b620f25dfabb67efe2eb3cfa0bf85,2013-05-07 00:00:00,107228,0,ARN,...,ARNZRHBKK,VI,L,Y,2013-05-30 19:35:00,2013-05-31 15:11:40,1.0,2013.0,5.0,NULL
9999991,2013-05-07 00:00:00,1P,SE,5924bc3bdf4f7a2461df897a9e41c56b,61f493dfd620a71b1301a4c65d55181b,ba3b620f25dfabb67efe2eb3cfa0bf85,2013-05-07 00:00:00,107228,0,ARN,...,BKKARN,DU,K,Y,2013-08-13 01:10:00,2013-08-13 06:43:09,1.0,2013.0,5.0,NULL
9999992,2013-05-07 00:00:00,1P,LB,4616f4fdfa96cda3ae144cafe96e4173,682ef1be33cfe9b4b988d95f6aefc8f7,5c2515732530386ee746ebb8ec8fb430,2013-05-07 00:00:00,87,563,BEY,...,BEYCAI,WO,K,Y,2013-05-11 14:05:00,2013-05-11 14:32:44,1.0,2013.0,5.0,NULL
9999993,2013-05-08 00:00:00,1P,LB,4616f4fdfa96cda3ae144cafe96e4173,682ef1be33cfe9b4b988d95f6aefc8f7,5c2515732530386ee746ebb8ec8fb430,2013-05-07 00:00:00,87,563,BEY,...,BEYCAI,WO,K,Y,2013-05-11 14:05:00,2013-05-11 14:32:44,-1.0,2013.0,5.0,NULL
9999994,2013-05-07 00:00:00,1P,US,83ccf07a55606976f78e63fcc805f58c,1490c3c5f95f04fa076fe15c775a80a9,1d746df73bdf7b7ec004889e9c98a87e,2013-05-07 00:00:00,1202,12412,JNB,...,JNBDXBICN,OU,U,Y,2013-05-12 14:10:00,2013-05-13 17:12:40,1.0,2013.0,5.0,NULL
9999995,2013-05-02 00:00:00,1A,FR,1d4b7849b31c41271a833dc4e5bea409,aa5d2b3223e699e1b67c2ff2b1d03325,70a80d683d7753c0f7f491d27da21393,2013-04-27 00:00:00,40266,0,ORY,...,ORYAAE,KS,T,Y,2013-08-19 14:55:00,2013-08-19 16:21:26,4.0,2013.0,5.0,NULL
9999996,2013-05-02 00:00:00,1A,FR,1d4b7849b31c41271a833dc4e5bea409,aa5d2b3223e699e1b67c2ff2b1d03325,70a80d683d7753c0f7f491d27da21393,2013-04-27 00:00:00,40266,0,ORY,...,AAEORY,KS,T,Y,2013-09-16 10:35:00,2013-09-16 14:01:26,4.0,2013.0,5.0,NULL
9999997,2013-05-03 00:00:00,1A,FR,1d4b7849b31c41271a833dc4e5bea409,aa5d2b3223e699e1b67c2ff2b1d03325,70a80d683d7753c0f7f491d27da21393,2013-04-27 00:00:00,40266,0,ORY,...,ORYAAE,KS,T,Y,2013-08-19 14:55:00,2013-08-19 16:21:26,-4.0,2013.0,5.0,NULL
9999998,2013-05-03 00:00:00,1A,FR,1d4b7849b31c41271a833dc4e5bea409,aa5d2b3223e699e1b67c2ff2b1d03325,70a80d683d7753c0f7f491d27da21393,2013-04-27 00:00:00,40266,0,ORY,...,AAEORY,KS,T,Y,2013-09-16 10:35:00,2013-09-16 14:01:26,-4.0,2013.0,5.0,NULL
9999999,2013-05-14 00:00:00,1A,IN,9e586aade06c70687736accbe5e98737,1032cd50f5b60ddef3e3f3f8e4285972,0fae61de5c249aaa28c2d573b589becf,2013-05-14 00:00:00,4003,2968,POM,...,POMBNEMEL,GK,Q,Y,2013-07-09 14:00:00,2013-07-09 21:20:24,2.0,2013.0,5.0,DELVS319B
10000000,2013-05-14 00:00:00,1A,IN,9e586aade06c70687736accbe5e98737,1032cd50f5b60ddef3e3f3f8e4285972,0fae61de5c249aaa28c2d573b589becf,2013-05-14 00:00:00,4003,2968,POM,...,MELADL,GK,V,Y,2013-07-12 07:10:00,2013-07-12 08:13:15,2.0,2013.0,5.0,DELVS319B
10000001,2013-05-28 00:00:00,1A,US,000a63dddc771356a09b2df81781d933,dda0cc56cd8e7e238cef9601d4ed7038,1df256f97e81f128fce7397753ce4a4f,2013-05-28 00:00:00,6388,0,MEM,...,MEMLAS,NV,L,Y,2013-11-03 08:30:00,2013-11-03 09:58:22,2.0,2013.0,5.0,NULL
10000002,2013-05-28 00:00:00,1A,US,000a63dddc771356a09b2df81781d933,dda0cc56cd8e7e238cef9601d4ed7038,1df256f97e81f128fce7397753ce4a4f,2013-05-28 00:00:00,6388,0,MEM,...,LASMEM,NV,L,Y,2013-11-07 13:30:00,2013-11-07 18:58:22,2.0,2013.0,5.0,NULL
10000003,2013-05-14 00:00:00,1A,LK,1a5585bef21f0bf8dc865a87843635f9,6ff8fd087f94799d7aed903683384775,3b339797f7eca14c24e8b7565da822c0,2013-05-14 00:00:00,13203,0,CMB,...,CMBMAA,FV,V,Y,2013-05-15 13:35:00,2013-05-15 15:08:39,1.0,2013.0,5.0,NULL
10000004,2013-05-14 00:00:00,1A,LK,1a5585bef21f0bf8dc865a87843635f9,6ff8fd087f94799d7aed903683384775,3b339797f7eca14c24e8b7565da822c0,2013-05-14 00:00:00,13203,0,CMB,...,MAACMB,FV,V,Y,2013-05-24 16:05:00,2013-05-24 17:38:39,1.0,2013.0,5.0,NULL
10000005,2013-05-18 00:00:00,1A,LK,1a5585bef21f0bf8dc865a87843635f9,6ff8fd087f94799d7aed903683384775,3b339797f7eca14c24e8b7565da822c0,2013-05-14 00:00:00,13203,0,CMB,...,MAACMB,FV,V,Y,2013-05-24 16:05:00,2013-05-24 17:38:39,-1.0,2013.0,5.0,NULL
10000006,2013-05-18 00:00:00,1A,LK,1a5585bef21f0bf8dc865a87843635f9,6ff8fd087f94799d7aed903683384775,3b339797f7eca14c24e8b7565da822c0,2013-05-14 00:00:00,6003,0,CMB,...,MAACMB,FV,V,Y,2013-05-19 16:05:00,2013-05-19 17:38:39,1.0,2013.0,5.0,NULL
10000007,2013-05-28 00:00:00,1A,US,07e98d2fd3cd4b737266b99727f7faa8,e8741eaf2fa2f71f931475d18fa72096,2b22597bdad931843c3b1d5219836e07,2013-05-28 00:00:00,328,1865,AUS,...,AUSDFWRDU,KK,Q,Y,2013-07-12 08:35:00,2013-07-12 15:03:14,1.0,2013.0,5.0,SEAEX38AA
10000008,2013-05-28 00:00:00,1A,FR,e2679367673d50f1ee085127d8a00eba,5f26f53ca29672815e0ee3bd93a2b0e4,4eb40315a7263131ae17712cd505b62a,2013-05-28 00:00:00,588,0,TLS,...,TLSORY,KP,S,Y,2013-06-04 10:50:00,2013-06-04 12:18:20,1.0,2013.0,5.0,LYSSR210Z
10000009,2013-05-28 00:00:00,1A,FR,e2679367673d50f1ee085127d8a00eba,5f26f53ca29672815e0ee3bd93a2b0e4,4eb40315a7263131ae17712cd505b62a,2013-05-28 00:00:00,588,0,TLS,...,ORYTLS,KP,S,Y,2013-06-04 19:10:00,2013-06-04 20:38:20,1.0,2013.0,5.0,LYSSR210Z

In [55]:
df_searches.columns

Index(['Date', 'Time', 'TxnCode', 'OfficeID', 'Country', 'Origin',
       'Destination', 'RoundTrip', 'NbSegments', 'Seg1Departure',
       'Seg1Arrival', 'Seg1Date', 'Seg1Carrier', 'Seg1BookingCode',
       'Seg2Departure', 'Seg2Arrival', 'Seg2Date', 'Seg2Carrier',
       'Seg2BookingCode', 'Seg3Departure', 'Seg3Arrival', 'Seg3Date',
       'Seg3Carrier', 'Seg3BookingCode', 'Seg4Departure', 'Seg4Arrival',
       'Seg4Date', 'Seg4Carrier', 'Seg4BookingCode', 'Seg5Departure',
       'Seg5Arrival', 'Seg5Date', 'Seg5Carrier', 'Seg5BookingCode',
       'Seg6Departure', 'Seg6Arrival', 'Seg6Date', 'Seg6Carrier',
       'Seg6BookingCode', 'From', 'IsPublishedForNeg', 'IsFromInternet',
       'IsFromVista', 'TerminalID', 'InternetOffice'],
      dtype='object')

In [61]:
top10 = df_booking.groupby('arr_port') ['pax'].sum()
top10

arr_port
AAB            30.0
AAE           810.0
AAL           810.0
AAN            20.0
AAQ          1650.0
AAR           500.0
ABA            90.0
ABB            40.0
ABE           880.0
ABI           150.0
ABJ          2600.0
ABK             0.0
ABQ          4290.0
ABR             0.0
ABS           310.0
ABT           300.0
ABV          1950.0
ABX           300.0
ABY            90.0
ABZ          3710.0
ACA           700.0
ACC          3810.0
ACE          1700.0
ACH            20.0
ACI            40.0
ACK           200.0
ACT           180.0
ACV           140.0
ACY           190.0
ADA           980.0
             ...
ZAZ            50.0
ZBF           110.0
ZBL            90.0
ZCL           150.0
ZCO           490.0
ZDH            60.0
ZFQ            40.0
ZFV           120.0
ZHA             0.0
ZIG            40.0
ZIH           870.0
ZLN             0.0
ZLO           500.0
ZNE          1510.0
ZNZ           970.0
ZOS            70.0
ZQN          1720.0
ZRH         20190.0
ZSA            10.0
ZSE            10.0
ZTH            50.0
ZUH            40.0
ZVE            40.0
ZVJ            20.0
ZVK            20.0
ZWE            30.0
ZWS           620.0
ZYL          1290.0
ZYN            20.0
ZYR          1020.0
Name: pax, Length: 2275, dtype: float64

In [69]:
top10.reset_index().sort_values('pax', ascending = False).head(10)

      arr_port      pax
1088  LHR       88809.0
1190  MCO       70930.0
1050  LAX       70530.0
1047  LAS       69630.0
886   JFK       66270.0
315   CDG       64490.0
216   BKK       59460.0
1228  MIA       58150.0
1719  SFO       58000.0
517   DXB       55590.0

## Ejercicio 2.3

In [70]:
import matplotlib.pyplot as plt
import matplotlib

In [71]:
df_searches.columns

Index(['Date', 'Time', 'TxnCode', 'OfficeID', 'Country', 'Origin',
       'Destination', 'RoundTrip', 'NbSegments', 'Seg1Departure',
       'Seg1Arrival', 'Seg1Date', 'Seg1Carrier', 'Seg1BookingCode',
       'Seg2Departure', 'Seg2Arrival', 'Seg2Date', 'Seg2Carrier',
       'Seg2BookingCode', 'Seg3Departure', 'Seg3Arrival', 'Seg3Date',
       'Seg3Carrier', 'Seg3BookingCode', 'Seg4Departure', 'Seg4Arrival',
       'Seg4Date', 'Seg4Carrier', 'Seg4BookingCode', 'Seg5Departure',
       'Seg5Arrival', 'Seg5Date', 'Seg5Carrier', 'Seg5BookingCode',
       'Seg6Departure', 'Seg6Arrival', 'Seg6Date', 'Seg6Carrier',
       'Seg6BookingCode', 'From', 'IsPublishedForNeg', 'IsFromInternet',
       'IsFromVista', 'TerminalID', 'InternetOffice'],
      dtype='object')

In [74]:
df_searches.head(5)

,Date,Time,TxnCode,OfficeID,Country,Origin,Destination,RoundTrip,NbSegments,Seg1Departure,...,Seg6Arrival,Seg6Date,Seg6Carrier,Seg6BookingCode,From,IsPublishedForNeg,IsFromInternet,IsFromVista,TerminalID,InternetOffice
0,2013-01-01,20:25:57,MPT,624d8c3ac0b3a7ca03e3c167e0f48327,DE,TXL,AUH,1.0,2.0,TXL,...,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,FRA
1,2013-01-01,10:15:33,MPT,b0af35b31588dc4ab06d5cf2986e8e02,MD,ATH,MIL,0.0,1.0,ATH,...,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,KIV
2,2013-01-01,18:04:49,MPT,3561a60621de06ab1badc8ca55699ef3,US,ICT,SFO,1.0,2.0,ICT,...,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,NYC
3,2013-01-01,17:42:40,FXP,1864e5e8013d9414150e91d26b6a558b,SE,RNB,ARN,0.0,1.0,RNB,...,NaN,NaN,NaN,NaN,1ASI,0,0,0,d41d8cd98f00b204e9800998ecf8427e,STO
4,2013-01-01,17:48:29,MPT,1ec336348f44207d2e0027dc3a68c118,NO,OSL,MAD,1.0,2.0,OSL,...,NaN,NaN,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,OSL

In [75]:
df_searches.dtypes

Date                  object
Time                  object
TxnCode               object
OfficeID              object
Country               object
Origin                object
Destination           object
RoundTrip            float64
NbSegments           float64
Seg1Departure         object
Seg1Arrival           object
Seg1Date              object
Seg1Carrier           object
Seg1BookingCode       object
Seg2Departure         object
Seg2Arrival           object
Seg2Date              object
Seg2Carrier           object
Seg2BookingCode       object
Seg3Departure         object
Seg3Arrival           object
Seg3Date              object
Seg3Carrier           object
Seg3BookingCode       object
Seg4Departure         object
Seg4Arrival           object
Seg4Date              object
Seg4Carrier           object
Seg4BookingCode       object
Seg5Departure         object
Seg5Arrival           object
Seg5Date              object
Seg5Carrier           object
Seg5BookingCode       object
Seg6Departure         object
Seg6Arrival           object
Seg6Date              object
Seg6Carrier           object
Seg6BookingCode       object
From                  object
IsPublishedForNeg     object
IsFromInternet        object
IsFromVista           object
TerminalID            object
InternetOffice        object
dtype: object

In [76]:
date_time = pd.to_datetime(df_searches['Date'] + ' ' + df_searches['Time'])
df_searches['DateTime'] = date_time

In [77]:
df_searches.dtypes

Date                         object
Time                         object
TxnCode                      object
OfficeID                     object
Country                      object
Origin                       object
Destination                  object
RoundTrip                   float64
NbSegments                  float64
Seg1Departure                object
Seg1Arrival                  object
Seg1Date                     object
Seg1Carrier                  object
Seg1BookingCode              object
Seg2Departure                object
Seg2Arrival                  object
Seg2Date                     object
Seg2Carrier                  object
Seg2BookingCode              object
Seg3Departure                object
Seg3Arrival                  object
Seg3Date                     object
Seg3Carrier                  object
Seg3BookingCode              object
Seg4Departure                object
Seg4Arrival                  object
Seg4Date                     object
Seg4Carrier                  object
Seg4BookingCode              object
Seg5Departure                object
Seg5Arrival                  object
Seg5Date                     object
Seg5Carrier                  object
Seg5BookingCode              object
Seg6Departure                object
Seg6Arrival                  object
Seg6Date                     object
Seg6Carrier                  object
Seg6BookingCode              object
From                         object
IsPublishedForNeg            object
IsFromInternet               object
IsFromVista                  object
TerminalID                   object
InternetOffice               object
DateTime             datetime64[ns]
dtype: object

In [84]:
import datetime

In [91]:
df_searches['Month'] = pd.DatetimeIndex(df_searches['DateTime']).month
df_searches.head(5)

,Date,Time,TxnCode,OfficeID,Country,Origin,Destination,RoundTrip,NbSegments,Seg1Departure,...,Seg6Carrier,Seg6BookingCode,From,IsPublishedForNeg,IsFromInternet,IsFromVista,TerminalID,InternetOffice,DateTime,Month
0,2013-01-01,20:25:57,MPT,624d8c3ac0b3a7ca03e3c167e0f48327,DE,TXL,AUH,1.0,2.0,TXL,...,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,FRA,2013-01-01 20:25:57,1.0
1,2013-01-01,10:15:33,MPT,b0af35b31588dc4ab06d5cf2986e8e02,MD,ATH,MIL,0.0,1.0,ATH,...,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,KIV,2013-01-01 10:15:33,1.0
2,2013-01-01,18:04:49,MPT,3561a60621de06ab1badc8ca55699ef3,US,ICT,SFO,1.0,2.0,ICT,...,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,NYC,2013-01-01 18:04:49,1.0
3,2013-01-01,17:42:40,FXP,1864e5e8013d9414150e91d26b6a558b,SE,RNB,ARN,0.0,1.0,RNB,...,NaN,NaN,1ASI,0,0,0,d41d8cd98f00b204e9800998ecf8427e,STO,2013-01-01 17:42:40,1.0
4,2013-01-01,17:48:29,MPT,1ec336348f44207d2e0027dc3a68c118,NO,OSL,MAD,1.0,2.0,OSL,...,NaN,NaN,1ASIWS,0,0,0,d41d8cd98f00b204e9800998ecf8427e,OSL,2013-01-01 17:48:29,1.0

In [87]:
df_searches.dtypes

Date                         object
Time                         object
TxnCode                      object
OfficeID                     object
Country                      object
Origin                       object
Destination                  object
RoundTrip                   float64
NbSegments                  float64
Seg1Departure                object
Seg1Arrival                  object
Seg1Date                     object
Seg1Carrier                  object
Seg1BookingCode              object
Seg2Departure                object
Seg2Arrival                  object
Seg2Date                     object
Seg2Carrier                  object
Seg2BookingCode              object
Seg3Departure                object
Seg3Arrival                  object
Seg3Date                     object
Seg3Carrier                  object
Seg3BookingCode              object
Seg4Departure                object
Seg4Arrival                  object
Seg4Date                     object
Seg4Carrier                  object
Seg4BookingCode              object
Seg5Departure                object
Seg5Arrival                  object
Seg5Date                     object
Seg5Carrier                  object
Seg5BookingCode              object
Seg6Departure                object
Seg6Arrival                  object
Seg6Date                     object
Seg6Carrier                  object
Seg6BookingCode              object
From                         object
IsPublishedForNeg            object
IsFromInternet               object
IsFromVista                  object
TerminalID                   object
InternetOffice               object
DateTime             datetime64[ns]
Month                       float64
dtype: object